# ML trading models

In [3]:
from backtesting.test import EURUSD, SMA

data = EURUSD.copy()
data

/home/darrendube/.local/lib/python3.10/site-packages/backtesting/test/__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.read_csv(join(dirname(__file__), filename),
/home/darrendube/.local/lib/python3.10/site-packages/backtesting/test/__init__.py:8: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  return pd.read_csv(join(dirname(__file__), filename),

                        Open     High      Low    Close  Volume
2017-04-19 09:00:00  1.07160  1.07220  1.07083  1.07219    1413
2017-04-19 10:00:00  1.07214  1.07296  1.07214  1.07260    1241
2017-04-19 11:00:00  1.07256  1.07299  1.07170  1.07192    1025
2017-04-19 12:00:00  1.07195  1.07280  1.07195  1.07202    1460
2017-04-19 13:00:00  1.07200  1.07230  1.07045  1.07050    1554
...                      ...      ...      ...      ...     ...
2018-02-07 11:00:00  1.23390  1.23548  1.23386  1.23501    2203
2018-02-07 12:00:00  1.23501  1.23508  1.23342  1.23422    2325
2018-02-07 13:00:00  1.23422  1.23459  1.23338  1.23372    2824
2018-02-07 14:00:00  1.23374  1.23452  1.23238  1.23426    4065
2018-02-07 15:00:00  1.23427  1.23444  1.22904  1.22904    6143

[5000 rows x 5 columns]

In [ ]:
def BBANDS(data, n_lookback, n_std):
    '''Bollinger bands indicator'''
    hlc3 = (data.High + data.Low + data.Close) / 3
    mean = hlc3.rolling(n_lookback).mean()
    std = hlc3.rolling(n_lookback).std()
    upper = mean + n_std*std
    lower = mean - n_std*std
    return upper, lower

close = data.Close.values
sma10 = SMA(data.Close, 10)
sma20 = SMA(data.Close, 20)
sma50 = SMA(data.Close, 50)
sma100 = SMA(data.Close, 100)
upper, lower = BBANDS(data, 20, 2)

# DESIGN MATRIX/ INDEPENDENT FEATURES
# Price-derived
data['X_SMA10'] = (close - sma10) / close
data['X_SMA20'] = (close - sma20) / close
data['X_SMA50'] = (close - sma50) / close
data['X_SMA100'] = (close - sma100) / close

data['X_DELTA_SMA10'] = (sma10 - sma20) / close
data['X_DELTA_SMA20'] = (close - sma20) / close